### ISSUE TITLE
Workspaces should be listed in alphabetical order

### ISSUE THREAD

**Issue by leebaird** [lanmaster53/recon-ng#15]
Workspaces should be listed in alphabetical order.

-- Feature request:
Add 2 columns: Created and Modified
Able to sort by all columns

**Comment by lanmaster53** [comment]
In the CLI output? There is no sorting of ascii tables in the CLI. Alphabetical order is doable though. 

Also, tracking modified would create an unnecessary and excessive number of queries due to the amount of writes that take place during the normal usage of a workspace. Honestly, the best way to track creation and modified dates is to look at the sqlite database file itself like so:

```
$ stat ~/.recon-ng/workspaces/{workspace}/data.db 
```

**Comment by lanmaster53** [comment]
Just pushed a change that handles 2/3 of this. The created time stamp is not worth the effort to make it work, as it is not cross-platform, and is not possible in Linux. See the linked article for further information. https://stackoverflow.com/questions/237079/how-to-get-file-creation-modification-date-times-in-python
