### ISSUE TITLE
multiple issues

### ISSUE THREAD

**Issue by sh1va73** [lanmaster53/recon-ng#17]
The show command is not working. When I do show modules , or show workspaces or show domains I get this result: show various framework items. But it shows nothing.

When I try to add domains , i get an error: Invalid command

I am running on last Kali version.

**Comment by lanmaster53** [comment]
Couple of things. First, have you looked at the wiki? 90% of the questions I get asked can be answered by looking through the wiki and watching the videos there. Give it a shot. I think you'll find what you are looking for. Second, I wouldn't be surprised if Kali is way behind on the version. They do some funky stuff in their repos and I have no control over it.

I'm going to go ahead an close this because your answers are in the wiki.

**Comment by sh1va73** [comment]
Thanks. It was a version issue indeed. I found out now.
