### ISSUE TITLE
Credit sn0int for registry/marketplace feature

### ISSUE THREAD

**Issue by kpcyrd** [lanmaster53/recon-ng#4]
hello!

congrats on the new release, really happy to see recon-ng is back. Not sure you've noticed, but I've been working on a modern reinterpretation of recon-ng in the meantime called [sn0int](https://github.com/kpcyrd/sn0int).

One of the core features is the registry I've introduced in late 2018 as an attempt to prevent one of the issues recon-ng ran into before the projects (temporary) inactivity.

The new marketplace feature in recon-ng looks very similar and the [documentation](https://github.com/lanmaster53/recon-ng/wiki/Features#module-marketplace) also reads slightly similar to [mine](https://sn0int.readthedocs.io/en/stable/usage.html#installing-the-default-modules) so I'm wondering if some of the ideas have been borrowed from my project.

If that's the case that's awesome and I'd appreciate if you could credit sn0int as an inspiration.

Thanks <3

**Comment by lanmaster53** [comment]
Thanks for reaching out.

I understand your concern. I'd be irritated if someone released software with what appeared to be my code and didn't provide attribution. However, in this case, I can assure you it is a coincidence, if anything.

I don't do OSINT as a part of my business, and haven't done it as a professional for years. I only maintain Recon-ng as a duty to the community, and because I love to write code. I literally have no idea what other tools exist for OSINT because I simply do not do it. So, not to say that it isn't a great tool, but I've never heard of sn0int.

I likely won't go look at the code, but I wouldn't be surprised if there are similarities. There are only so many ways you can integrate external modularity into a command line tool. I'm not sure if you follow me on Twitter, but it would have been mighty bold and dishonest of me to tweet [this](https://twitter.com/LaNMaSteR53/status/1143324202377891842) last week if I knew there was another tool already doing, AND I had copied it.

Once again, I appreciate your concern. I never hold back credit where it is due, but in this case, it simply isn't. I hope you understand.
