### ISSUE TITLE
Namchk api closed source

### ISSUE THREAD

**Issue by anoduck** [lanmaster53/recon-ng#48]
First off, much love. I use to use this framework a lot and loved it. It was brilliantly written, and there is definitely a case of beer with your name on it. This framework also was the first, I cut my developmental teeth on, so there is a little sentimental attachment. But, there has been a steady movement towards the use of paid APIs in maturing of the framework, and although they may make life easier for the programmer, and you deserve it. It makes technology less accessible for young developers and college students who can not afford to legitimize the expense of a glob of paid APIs. For example, namchk.com. The namchk module use to work brilliantly, but now requires a paid api. I have written the company about offering an educational deal, for those of us performing educational research, to which they informed me to jump in a lake. Which was irritating. 
You can close out this issue upon reading it. I just wanted to provide some feedback, because I am sad to see the framework move into the realm of closed. Thanks again.

**Comment by lanmaster53** [comment]
Yeah, that does suck. And I've encountered similar situations. All I can say is that Recon-ng remains free and I welcome new modules that leverage free resources to replace some of the old ones that have gone to a fee-based model. I have no say in what modules get developed by the community or how third parties react to increased traffic, but as companies realize the value of their information, they typically turn it into a revenue stream. This has been happening since long before Recon-ng, and will continue forever. It's an unfortunate side effect of capitalism. The key is to find new free resources and write modules for those.

Thanks for the feedback!
