### ISSUE TITLE
Syntax error on start up

### ISSUE THREAD

**Issue by Artook10** [lanmaster53/recon-ng#69]
Just installed Recon-ng but when I am starting the program I get this syntax error:

File "./recon-ng", line 16
    print(f"{Colors.R}[!] Module 'readline' not available. Tab complete disabled.{Colors.N}")

Has a modification been done on this line?

       Art

**Comment by AnonPK3** [comment]
I can verify this same error. Using a Raspberry Pi 3 running Raspbian with latest updated packages.
For shits and grins tried the pip REQUIREMENTS patch, did not solve the problem. Failed with the json error. Tried the json patch and it just made things worse. Newbie lucky to get this far.

**Comment by Artook10** [comment]
I should have added that I am using linux Mint 18.2  on Asus laptop.

**Comment by AnonPK3** [comment]
My system info using uname -a : Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

**Comment by lanmaster53** [comment]
That's what happens when you try to run it with Python < 3.6 because f-string formatting didn't exist then and this is the first line of code that uses it.

https://github.com/lanmaster53/recon-ng/wiki/Getting-Started#prerequisites

**Comment by AnonPK3** [comment]
Thanks for the info. Damn. Python 3.5.3 is so close. If I felt more confident of my skills, I would manually install Python. Linux is a struggle for me.

Sent from my iPhone

On Feb 13, 2020, at 8:08 PM, lanmaster53 <notifications@github.com<mailto:notifications@github.com>> wrote:


That's what happens when you try to run it with Python < 3.6 because f-string formatting didn't exist then and this is the first line of code that uses it.

https://github.com/lanmaster53/recon-ng/wiki/Getting-Started#prerequisites

**Comment by Artook10** [comment]
Thank you for the information will install 3.7 as soon as I can  and hope
for the best.

**Comment by lanmaster53** [comment]
Awesome. Closing.
