### ISSUE TITLE
Just installed recon-ng on Arch Linux

### ISSUE THREAD

**Issue by brenosilvera1** [lanmaster53/recon-ng#99]
I just installed recon-ng and it's not starting. Found this [issue](https://github.com/lanmaster53/recon-ng/issues/8) but is not very helpful. As you can see, the python version I'm using is 3.8.3.

![recon-ng_bug](https://user-images.githubusercontent.com/39427845/83340857-768cb500-a2b3-11ea-8961-0dbed2b8e19e.png)

**Comment by lanmaster53** [comment]
I am not at all familiar with your installation method. However, the error that you are getting seems to be related to "f" string formatting, which has been around since well before Python 3.8.3. Could you be having some sort of environment confusion? Check the shebang line of the `recon-ng` file and see if it is invoking the wrong version of Python on your system.

**Comment by lanmaster53** [comment]
Closed due to lack of response.
